//
//  DevicesModels.swift
//  hOme
//
//  Created by Coldefy Yoann on 2016/05/29.
//  Copyright (c) 2016年 YoannColdefy. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

struct Devices_FetchDevices_Request {
}

struct Devices_FetchedDevices_Response {
	var devices: [DeviceProtocol]
}

struct Devices_FetchDevices_ViewModel {
	struct DisplayDevice {
		var internalName: String
		var name: String
	}
	
	var displayedDevices: [DisplayDevice]
}
