//
//  DevicesViewController.swift
//  hOme
//
//  Created by Coldefy Yoann on 2016/05/29.
//  Copyright (c) 2016年 YoannColdefy. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol DevicesViewControllerInput {
	
	func displayFetchedDevices(viewModel: Devices_FetchDevices_ViewModel)
}

protocol DevicesViewControllerOutput {
	func fetchDevices(request: Devices_FetchDevices_Request)
//	func doSomething(request: DevicesRequest)
}

class DevicesViewController: UITableViewController {
	var output: DevicesViewControllerOutput!
	var router: DevicesRouter!
	
	// MARK: Object lifecycle
	
	override func awakeFromNib() {
		super.awakeFromNib()
		DevicesConfigurator.sharedInstance.configure(self)
	}
	
	// MARK: View lifecycle
	
	override func viewDidLoad() {
		super.viewDidLoad()
		fetchDevicesOnLoad()
	}
	
	// MARK: Event handling
	
	func fetchDevicesOnLoad() {
		let request = Devices_FetchDevices_Request()
		output.fetchDevices(request)
	}
	
	// MARK: Display logic
	
	
}

extension DevicesViewController: DevicesViewControllerInput {
	func displayFetchedDevices(viewModel: Devices_FetchDevices_ViewModel) {
		// NOTE: Display the result from the Presenter
		
		// nameTextField.text = viewModel.name
	}
}
