//
//  DevicesRouter.swift
//  hOme
//
//  Created by Coldefy Yoann on 2016/05/29.
//  Copyright (c) 2016年 YoannColdefy. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol DevicesRouterInput {
	func passDataToDeviceView(segue: UIStoryboardSegue, device: DisplayDevice)
}

class DevicesRouter: DevicesRouterInput {
	weak var viewController: DevicesViewController!
	
	// MARK: Navigation
	
	
	// MARK: Communication
	
//	func passDataToNextScene(_ segue: UIStoryboardSegue) {
//		// NOTE: Teach the router which scenes it can communicate with
//		
//		if segue.identifier == "ShowSomewhereScene" {
//			passDataToSomewhereScene(segue)
//		}
//	}
	
	func passDataToDeviceView(segue: UIStoryboardSegue, device: DisplayDevice) {
		if let deviceviewController = segue.destination as? DeviceViewController {
			deviceviewController.setDevice(internalName: device.internalName)
		}
	}
	

}
