//
//  CreateDevicePresenter.swift
//  hOme
//
//  Created by Coldefy Yoann on 2016/05/21.
//  Copyright (c) 2016年 YoannColdefy. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol CreateDevicePresenterInput {
	func presentConnectors(_ response: CreateDevice_GetConnectors_Response)
	func setDoneButtonState(_ response: CreateDevice_ValidateDoneButtonState_Response)
	func presentCouldCreateDevice(_ response: CreateDevice_CreateDevice_Response)
}

protocol CreateDevicePresenterOutput: class {
	func displayConnectors(_ connectorsInfo: CreateDevice_GetConnectors_ViewModel)
	func setDoneButtonState(_ viewModel: CreateDevice_ValidateDoneButtonState_ViewModel)
	func dissmissView()
}

class CreateDevicePresenter: CreateDevicePresenterInput {
	weak var output: CreateDevicePresenterOutput!
	
	// MARK: Presentation logic
	
	func presentConnectors(_ response: CreateDevice_GetConnectors_Response) {
		// NOTE: Format the response from the Interactor and pass the result back to the View Controller
		let connectorTypes = formatConnectorTypes(response.connectorsTypes)
		let connectors = formatConnectors(response.connectorsByType)

		
		let viewModel = CreateDevice_GetConnectors_ViewModel(connectorsTypes: connectorTypes, connectors: connectors)
		output.displayConnectors(viewModel)
	}
	
	private func formatConnectorTypes(_ connectorsTypes: [ConnectorType]) -> [String] {
		var connectorTypesNames = [String]()
		for connectorType in connectorsTypes {
			switch connectorType {
			case .irKit: connectorTypesNames.append("IRKit")
			}
		}
		return connectorTypesNames
	}
	
	private func formatConnectors(_ connectorsByType: [ConnectorType: [Connector]]) -> [[CreateDevice_GetConnectors_ViewModel.connectorName]] {
		var connectorNamesByType: [[CreateDevice_GetConnectors_ViewModel.connectorName]] = []
		for connectorType in connectorsByType.keys {
			var connectorsNames: [CreateDevice_GetConnectors_ViewModel.connectorName] = []
			if let connectorsOfType = connectorsByType[connectorType] {
				for connector in connectorsOfType {
					let connectorName = CreateDevice_GetConnectors_ViewModel.connectorName(name: connector.name, internalName: connector.internalName)
					connectorsNames.append(connectorName)
				}
			}
			connectorNamesByType.append(connectorsNames)
		}
		return connectorNamesByType
	}
	
	func setDoneButtonState(_ response: CreateDevice_ValidateDoneButtonState_Response) {
		output.setDoneButtonState(CreateDevice_ValidateDoneButtonState_ViewModel(doneButtonEnabled: response.doneButtonEnabled))
	}
	
	func presentCouldCreateDevice(_ response: CreateDevice_CreateDevice_Response) {
		if response.couldCreateDevice {
			output.dissmissView()
		}
	}
}
