//
//  CreateDeviceModels.swift
//  hOme
//
//  Created by Coldefy Yoann on 2016/05/21.
//  Copyright (c) 2016年 YoannColdefy. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

struct CreateDeviceRequest {
	var name: String
	var connectorInternalName: String
}

struct CreateDevice_GetConnectors_Response {
	var connectorsTypes: [ConnectorType]
	var connectorsByType: [ConnectorType: [Connector]]
}

struct CreateDevice_GetConnectors_ViewModel {
	struct connectorName {
		var name: String
		var internalName: String
		
		func Equal(other: connectorName) -> Bool {
			return (name == other.name) && (internalName == other.internalName)
		}
	}
	var connectorsTypes: [String]
	var connectors: [[connectorName]]
}
