//
//  CreateDeviceModels.swift
//  hOme
//
//  Created by Coldefy Yoann on 2016/05/21.
//  Copyright (c) 2016年 YoannColdefy. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

struct CreateDeviceRequest {
	var name: String
	var connectorName: String
}

struct CreateDevice_GetConnectors_Response {
	var connectorsTypes: [ConnectorType]
	var connectorsByType: [ConnectorType: [Connector]]
}

struct CreateDevice_GetConnectors_ViewModel {
	var connectorsTypes: [String]
	var connectors: [[String]]
}
