//
//  GetConnectorsWorker.swift
//  hOme
//
//  Created by Coldefy Yoann on 2016/05/21.
//  Copyright (c) 2016年 YoannColdefy. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

extension GetConnectorsWorker: ApplicationUser {
	
}

class GetConnectorsWorker {
	// MARK: Business Logic
	
	func getConnectorTypes() -> [ConnectorType] {
		if let application = application {
			return application.getConnectorsTypes()
		}
		return [ConnectorType]()
	}
	
	func getConnectorsByType() -> [ConnectorType: [Connector]] {
		if let application = application {
			return application.getConnectorsByType()
		}
		return [ConnectorType: [Connector]]()
	}
}
